### ISSUE TITLE
Doesn't work in Google App Engine environment

### ISSUE THREAD

**Issue by rusy** [valyala/quicktemplate#13]
[Google App Engine Go Standard Environment](https://cloud.google.com/appengine/docs/go/) has no _unsafe_ package, so running the simple Hello example gives the following error:
> 
2016/07/03 22:23:53 go-app-builder: Failed parsing input: parser: bad import "unsafe" in github.com/valyala/quicktemplate/bytebuffer.go from GOPATH

Is it possible to have an option to run it without "unsafe" package (even with price of lower performance)?

**Comment by valyala** [comment]
Done.

The performance may be not so fast, since `unsafe` package was used for zero-allocation conversions between `string` and `[]byte`. Below is benchmark results' comparison for the original `quicktemplate` version and the version adapted for AppEngine:

```
benchmark                                   original ns/op     appengine ns/op     delta
BenchmarkMarshalJSONQuickTemplate1-4        196           370           +88.78%
BenchmarkMarshalJSONQuickTemplate10-4       922           1940          +110.41%
BenchmarkMarshalJSONQuickTemplate100-4      8250          18150         +120.00%
BenchmarkMarshalJSONQuickTemplate1000-4     84661         182671        +115.77%
BenchmarkMarshalXMLQuickTemplate1-4         179           385           +115.08%
BenchmarkMarshalXMLQuickTemplate10-4        722           1767          +144.74%
BenchmarkMarshalXMLQuickTemplate100-4       6307          16017         +153.96%
BenchmarkMarshalXMLQuickTemplate1000-4      64188         158076        +146.27%
BenchmarkQuickTemplate1-4                   145           324           +123.45%
BenchmarkQuickTemplate10-4                  538           1382          +156.88%
BenchmarkQuickTemplate100-4                 4853          12668         +161.03%
```

The following commands were used for running benchmarks:

```
# original
go test -bench=Quick -benchmem github.com/valyala/quicktemplate/tests

# appengine
go test -tags=appengine -bench=Quick -benchmem github.com/valyala/quicktemplate/tests
```
