### ISSUE TITLE
Quick start issue!

### ISSUE THREAD

**Issue by cydside** [valyala/quicktemplate#16]
Hi,
I followed the quick start steps but running the main.go (go run main.go) here is the error message showed:

../github.com/valyala/quicktemplate/bytebuffer.go:4:2: cannot find package "github.com/valyala/bytebufferpool" in any of:
	/usr/lib/go-1.6/src/github.com/valyala/bytebufferpool (from $GOROOT)
	/home/danilo/godev/src/github.com/valyala/bytebufferpool (from $GOPATH)

Could you please fix it?
Thanks,
Danilo

**Comment by valyala** [comment]
Just run the following command from your shell:
```
go get -u github.com/valyala/bytebufferpool
```

**Comment by cydside** [comment]
Yes, I get it. It's just to make you aware about that and fix the Quick start guide. Anyway, thank you for your reply and the nice job.
