### ISSUE TITLE
Feature Request: Change package name

### ISSUE THREAD

**Issue by jeremylowery** [valyala/quicktemplate#22]
First off, thanks for the great template library. Coming from mako, I feel right at home with quicktemplate.

Currently quicktemplate only outputs the name of the directory as the package name in the generated go code. Would it be possible to allow the package name to be changed from a {% package %} directive at the top of the template?

My use case is that I have a few templates that I want to drop into the main package alongside other code. I'd like to be able to specify {% package "main" %}

I surveyed the code to take a look at how to implement it. I guess the packageName would have to be exposed by the scanner somehow to get it back up to the parser.

**Comment by valyala** [comment]
This sounds reasonable. Will implement it in the near future.

**Comment by valyala** [comment]
Now the package name may be overridden with:

```qtpl
{% package newPackageName %}
Here is a template
```

**Comment by jeremylowery** [comment]
This is great.thank you very much!

**Comment by valyala** [comment]
@jeremylowery , do not forget updating `qtc` before using this feature:
```
go get -u github.com/valyala/quicktemplate/...
```
