### ISSUE TITLE
Run qtc on a folder

### ISSUE THREAD

**Issue by basharov** [valyala/quicktemplate#23]
Is it possible to set a folder where my templates are located that I want to be compiled?

Something like this 
```
qtc --folder=/my/long/path/templates
```

Thanks!

**Comment by valyala** [comment]
Yes, just use `-dir` instead of `-folder`:
```
qtc -dir=/my/long/path/templates
```

See `qtc -h` output and [qtc README](https://github.com/valyala/quicktemplate/blob/master/qtc/README.md) for details.
