### ISSUE TITLE
Possible to import html files?

### ISSUE THREAD

**Issue by abenz1267** [valyala/quicktemplate#26]
Hello,

is it possible to import html files and QTC still interpreting quicktemplate syntax? Cat will import the html as a string and therefore ignore quicktemplate syntax for variables etc.

Reason is: working with .qtpl files without html autocomplete etc. is somewhat tiresome.....

Did i miss something?

Regards

**Comment by erginduran** [comment]
+1

**Comment by valyala** [comment]
`qtpl` is the default extension for `quicktemplate` files. It may be overridden with `-ext` parameter. For instance, the following `go:generate` rule will compile only files with `html` extension.

```go
//go:generate qtc -dir=path/to/directory/with/templates -ext=html
```

See more details [in the qtc README](https://github.com/valyala/quicktemplate/blob/master/qtc/README.md).
