### ISSUE TITLE
Feature request: strip newline

### ISSUE THREAD

**Issue by hardcoar** [valyala/quicktemplate#27]
Title says everything. we have strip/collapse space. 

Is there any way to collapse newline too?
the resulting html will be similar to minified html and that would be awesome!

cheers

**Comment by valyala** [comment]
Both `{% stripspace %}` and `{% collapsespace %}` should strip newlines. Try this:

```qtpl
{% stripspace %}
{% func collapseNewlines() %}
<html>
    <head>
        <title>
            foobar
        </title>
    </head>
    <body>
        test
    </body>
</html>
{% endfunc %}
{% endstripspace %}
```

`collapseNewlines()` should return:

```
<html><head><title>foobar</title></head><body>test</body></html>
```
