### ISSUE TITLE
A way to get template as []byte?

### ISSUE THREAD

**Issue by justmax437** [valyala/quicktemplate#28]
By now i can only see a way to retrive generated template as a string (or write it directly to io.Writer). It would be nice to also have a possibility to retrive it as []byte, without overhead of []byte-string-[]byte conversion.

**Comment by valyala** [comment]
Just use [bytes.Buffer](https://golang.org/pkg/bytes/#Buffer) as `io.Writer`:

```go
var buf bytes.Buffer

// Pass buf into the corresponding Write* function for the template function
WriteFoobar(&buf)

// Obtain byte slice
b := buf.Bytes()

UseByteSlice(b)

// Now the buffer may be re-used - just call buf.Reset() on it
```
