### ISSUE TITLE
Escape ampersand and single quote?

### ISSUE THREAD

**Issue by escholtz** [valyala/quicktemplate#3]
Looks like the escaper in the html package escapes single quotes:
https://golang.org/src/html/escape.go?s=3992:4005#L172

It appears that quicktemplate does not. Is that safe?

**Comment by valyala** [comment]
quicktemplate should escape single quotes - see [the corresponding code](https://github.com/valyala/quicktemplate/blob/master/htmlescapewriter.go) and [this test](https://github.com/valyala/quicktemplate/blob/master/htmlescapewriter_test.go#L10).

Could you provide a short `quicktemplate` example, which doesn't escape single quote?

**Comment by escholtz** [comment]
Ooops, you are correct. Thanks for the quick response and sorry for wasting your time.

On 2nd glance, looks like the html package also remaps `&` to `&amp;`. Does that need to be added?

Test:
```
{% func TestEscapeAmpersand() %}
  {%s "&" %}
{% endfunc %}
```

**Comment by valyala** [comment]
> looks like the html package also remaps & to &amp;. Does that need to be added?

Yes! Fixed it!
