### ISSUE TITLE
New VS Code quicktemplate language definition

### ISSUE THREAD

**Issue by atomi** [valyala/quicktemplate#38]
I made a quicktemplate VS Code language extension. It's very simple, just basic syntax highlighting.

https://marketplace.visualstudio.com/items?itemName=vsatomi.vscode-quicktemplate#overview

Thanks.

**Comment by frederikhors** [comment]
@atomi Is the project still alive?

**Comment by atomi** [comment]
No. Feel free to fork.

**Comment by frederikhors** [comment]
@atomi can I ask you why? Are you still using quicktemplate? Anything else?

**Comment by atomi** [comment]
Yes.

**Comment by frederikhors** [comment]
Yes what? Quicktemplate? And if yes, which IDE/editor/tool?
