### ISSUE TITLE
collapsespace strips space after quicktemplate tag

### ISSUE THREAD

**Issue by snabb** [valyala/quicktemplate#39]
I have the following template:
```
{% collapsespace %}
{% func Foo(str string) %}
  Foo {%s str %} bar.
{% endfunc %}
{% endcollapsespace %}
```
I call this template `templates.WriteFoo(out, "string")`.

I get the following output:

> Foo stringbar.

I think this is a bug. It should leave one space after the output tag (now it strips all) when `collapsespace` is in effect.

**Comment by Allendar** [comment]
Try your syntax like this:

```
{% func Foo(str string) %}{% collapsespace %}
  Foo {%s str %}{% space %}bar.
{% endcollapsespace %}{% endfunc %}
```

It probably only leaves a space on one side due to the order it renders the inline function and the stripping.

You can probably also call the function just with `{%s Foo("string") %}` (if executing inside a template).

**Comment by valyala** [comment]
The issue should be fixed now
