### ISSUE TITLE
Switch case (Question)

### ISSUE THREAD

**Issue by hardcoar** [valyala/quicktemplate#4]
how will i implement switch using quicktemplate?

**Comment by valyala** [comment]
Currently switch statement may be emulated via `if - elseif - endif`:

```
{% if foo() %}
  foo
{% elseif bar() %}
  bar
{% elseif baz() %}
  baz
{% endif %}
```

I'm thinking about adding `switch` statement support to quicktemplate...

**Comment by valyala** [comment]
Just added switch statement support to quicktemplate:

```qtpl
{% switch foo() %}
{% case "bar" %}
    bar
{% case "baz" %}
   baz
{% default %}
   {%s foo() %}
{% endswitch %}
```
