### ISSUE TITLE
Line numbers in panic are incorrect

### ISSUE THREAD

**Issue by danielparks** [valyala/quicktemplate#51]
The line numbers generated in panic messages from `go` are incorrect. For example:

~~~
ERRO[0002] panic: runtime error: invalid memory address or nil pointer dereference web/templates.(*EventsShow).StreamBodyHTML
	web/templates/events-show.qtpl:56
~~~

The actual error is on a much earlier line.

The issue can be resolved by removing the tabs before each `//line` comment.

**Comment by valyala** [comment]
This should be fixed starting from [v1.1.1](https://github.com/valyala/quicktemplate/tree/v1.1.1)
