### ISSUE TITLE
cat in func with parameters

### ISSUE THREAD

**Issue by frederikhors** [valyala/quicktemplate#60]
I'm trying to understand `cat`.

In readme I can read:

```md
{% cat "/path/to/file" %}:

Cat emits the given file contents as a plaintext:
{% func passwords() %}
    /etc/passwd contents:
    {% cat "/etc/passwd" %}
{% endfunc %}
```

I'm trying to use something like this but with a parameter:

```md
{% func passwords(user string) %}
    /etc/passwd contents for user:
    {% cat "/etc/" + user + "/passwd" %}
{% endfunc %}
```

But the compiler returns an error: `invalid syntax`.

**How can I do?**
Is it possible?

**Comment by valyala** [comment]
Unfortunately this isn't possible.  `{% cat %} ` expands during template compilation, so it accepts only quoted string as file path. Dynamic `cat` can be implemented with [ioutil.ReadFile](https://golang.org/pkg/io/ioutil/#ReadFile):

```qtpl
{% import "io/ioutil" %}

{% func passwords(user string) %}
    {% code
        filename := "/etc/" + user + "/passwd"
        data, err := ioutil.ReadFile(filename)
    %}
    {% if err != nil %}
        cannot open {%q filename %}: {%s err.Error() %}
    {% else %}
        {%z= data %}
    {% endif %}
{% endfunc %}
```

**Comment by frederikhors** [comment]
No @valyala I'm fine with expansion at compile time.

What I'm looking now is a way to "import" .svg files (at compile time).

Let's say I have a sidebar with many svg icons and a single `func SidebarItem()` to create each one.

In that function I need `{% cat parameter %}` where `parameter = "../correct/path"`.

Do you think it is possible?

Is there another way?

**Comment by frederikhors** [comment]
**UPDATE:**

I'm using this way because I come from React and my mind is all about components.

So I can use something like this:

**Comment by valyala** [comment]
Unfortunately this doesn't work, since `qtpl` cannot perform constant string propagation to function calls :(

There is the following ugly workaround:

```qtpl
{% func sidebarItemHeader(href string) %}
  <a class="sidebar-icon" href="{%s href %}">
    <svg class="svg-icon">
{% endfunc %}

{% func sidebarItemFooter() %}
    </svg>
  </a>
{% endfunc %}
```

and

```qtpl
{%= sidebarItemHeader("/first-link") %}{% cat "../path/to/file1.svg" %}{%= sidebarItemFooter() %}
{%= sidebarItemHeader("/another-link") %}{% cat "../path/to/file2.svg" %}{%= sidebarItemFooter() %}
{%= sidebarItemHeader("/a-link") %}{% cat "../path/to/file3.svg" %}{%= sidebarItemFooter() %}
```

**Comment by frederikhors** [comment]
Yes, this is definitely a solution although ugly.

What do you think about using a `func` for every icon?

```
{% func SvgIcon1() %}
    {% cat "../svg/SvgIcon1.svg" %}
{% endfunc %}

{% func SvgIcon2() %}
    {% cat "../svg/SvgIcon2.svg" %}
{% endfunc %}

{% func SvgIcon3() %}
    {% cat "../svg/SvgIcon3.svg" %}
{% endfunc %}

{% func SvgIcon4() %}
    {% cat "../svg/SvgIcon4.svg" %}
{% endfunc %}

{% func SvgIcon5() %}
    {% cat "../svg/SvgIcon5.svg" %}
{% endfunc %}
```

Calling it in code with: `{%= SvgIcon5() %}`.

It works but I don't know the performances implications.

**What do you think?**

**Comment by valyala** [comment]
This solution should work too

**Comment by frederikhors** [comment]
And for performances? Your one or mine? I think your is better because no new `funcs`. Right?

_After your last answer I can close this issue._

**Comment by valyala** [comment]
Both solutions should have comparable performance
