### ISSUE TITLE
Hash in files name but not in development

### ISSUE THREAD

**Issue by frederikhors** [valyala/quicktemplate#61]
Coming from javascript frontend world I'm wondering how to use hash when importing or referencing files in templates.

I wanna develop with this code:

```
{% func Page(p Page) %}
  <html>
  <head>
    <link rel="stylesheet" href="/static/css/base.css"/>
  </head>
  <body>
    {%= p.Body() %}
  </body>
  </html>
{% endfunc %}
```

and deploy with this code:

```
{% func Page(p Page) %}
  <html>
  <head>
    <link rel="stylesheet" href="/static/css/base-4ab5f2de4.css"/>
  </head>
  <body>
    {%= p.Body() %}
  </body>
  </html>
{% endfunc %}
```

- before: `base.css`
- after: `base-4ab5f2de4.css`

**Is it possible today?**

- What do you think about using an ENV VAR at compile time to switch behaviour (DEVELOP/PRODUCTION) and calculate every hash with a function?

- What do you use today for cache invalidation?

This is useful also for adding CDN addresses in future, right?

Something similar (abandoned): https://github.com/defrankland/hasherator.

**Comment by frederikhors** [comment]
I just found 4 days ago this post on reddit: https://www.reddit.com/r/golang/comments/co0vyr/collect_and_hash_static_file_names_for_go/

And the project: https://github.com/catcombo/go-staticfiles

**Comment by valyala** [comment]
The easiest approach would be to create url generation function and call it from the template:

somewhere in Go package `util`:
```go
var env = flag.String("env", "dev", "Environment. Hashes are appended to static urls if -env=prod")

func StaticUrlWithOptionalHash(path string) string {
    if *env != "prod" {
        return path
    }
    hash := getCachedHashForFilePath(path)
    ext := filepath.Ext(path)
    pathNoExt := path[:len(path)-len(ext)]
    return fmt.Sprintf("%s-%s%s", pathNoExt, hash, ext)
}
```

and

```qtpl
{% import "path/to/util" %}

{% func Page() %}
<head>
    <link rel="stylesheet" href="{%s util.StaticUrlWithOptionalHash("/static/css/base.css") %}"/>
  </head>
{% endfunc %}
```

**Comment by frederikhors** [comment]
Amazing. I'm trying to make it works with https://github.com/catcombo/go-staticfiles and after that I can close this issue.

**Comment by frederikhors** [comment]
I'm done with https://github.com/catcombo/go-staticfiles. Amazing project. Thanks for your answer @valyala. As always, you prove to be a wonderful person. Thanks.
