### ISSUE TITLE
Different slash for different OS

### ISSUE THREAD

**Issue by frederikhors** [valyala/quicktemplate#62]
I'm using unix, mac, windows with many projects and when I regenerate code on different OS qtc writes different slash in each commented line:

Example on mac:

`//line project/templates/include_custom.qtpl:3`

Example on Windows:

`//line project\templates\include_custom.qtpl:3`

Can we use the same slash every time please?

What do you think about it?

**Comment by valyala** [comment]
Done in [v1.2.0](https://github.com/valyala/quicktemplate/tree/v1.2.0).

**Comment by frederikhors** [comment]
It works great thanks.
