### ISSUE TITLE
Multiline attribute is broken when using stripspace

### ISSUE THREAD

**Issue by arch-mage** [valyala/quicktemplate#68]
**template**
```
{% stripspace %}
{% func Page() %}
<form
  method="post"
>
  <input
    type="text"
    />
</form>
{% endfunc %}
{% endstripspace %}
```
**output**
```html
<formmethod="post"><inputtype="text"/></form>
```
**expected output**
```html
<form method="post"><input type="text"/></form>
```

**Comment by valyala** [comment]
`{%stripspace%}` strips all the whitespace between lines. Try using`{%collapsespace%}` instead, which collapses whitespace between lines into a single space. Another solution is to insert explicit `{%space%}`, which is never removed.

**Comment by arch-mage** [comment]
Oh, I see. I miss understood.
