### ISSUE TITLE
Suggestion qtc: Add a watcher qtc -w

### ISSUE THREAD

**Issue by kataras** [valyala/quicktemplate#7]
Add a watcher subcommand/flag for example ` qtc -w ./ -d ./templates` -> watch and compile on file changes in the current directory, serve the compiled files in the ./templates directory. 

You can use fsnotify package, I will do that on iris but it will be nice to have it build'n with qtc :) 

P.S: I don't know if go generate has a watch command but I doubt

**Comment by nkev** [comment]
I'm not sure how this would work. Quicktemplate only creates *.go files by running `go generate`. You could automate that with fsnotify but then you also have to recompile the whole application right?

**Comment by valyala** [comment]
This requires recompilation of the whole application. I doubt `qtc` is a good level for such a functionality. Probably a separate watcher app may be created instead for automatic recompilation on template files' modifications.

**Comment by nkev** [comment]
@valyala Yes, this is a problem with most of the good Go templating engines, except the ones that don't generate source code (like Jet). Every time you make the smallest change in any template, you have to run `go generate` and then recompile the whole app. I looked at Jet, but it uses reflection, which I hate. Would you consider adding basic `include`, `for-each` and `if-then` functionality to Fasttemplate? That's all we really need.

**Comment by kataras** [comment]
Yes, you're right , the whole application needs to be re-compiled... I'm closing this issue and sorry I should know that

**Comment by valyala** [comment]
> Would you consider adding basic include, for-each and if-then functionality to Fasttemplate?

I don't want complicating fasttemplate. So it would be better just using [Jet](https://github.com/CloudyKit/jet). It looks like it is the fastest template engine for go at the moment, which doesn't require source code recompilation after each modification.

**Comment by stereosteve** [comment]
[modd](https://github.com/cortesi/modd) is a nice tool I just found to handle this.

Here is my `modd.conf` file for quicktemplate:

```
**/*.qtpl {
    prep: qtc
}

**/*.go {
    prep: go build -o devbuild
    daemon: ./devbuild
}

devbuild {
    daemon: devd --livewatch --modd http://localhost:8080
}
```

The last part at the bottom it uses [devd](https://github.com/cortesi/devd) from the same author to work with livereload.  That part can be removed if you don't want livereload.

**Comment by valyala** [comment]
@stereosteve , this is awesome!

**Comment by stereosteve** [comment]
@valyala thanks for quicktemplate!  It is so much better than `text/template`.  If I could double star it I would.
