### ISSUE TITLE
Uint32 and Uint64 support?

### ISSUE THREAD

**Issue by diegomontoya** [valyala/quicktemplate#74]
I do not see uint support. DL (int64) cannot handle uint32. Thanks if I missed it in docs.

**Comment by valyala** [comment]
There are no functions for efficient printing of `uint64`. The following workaround could be used for printing `u32` value of type `uint32`:
```qtpl
{%dl int64(u32) %}
```

As for `uint64`, then there is the following (not very efficient) workaround:

```qtpl
{%s= fmt.Sprintf("%d", u64) %}
```

I'm open to pull requests for printing `uint64` and `uint32` via special tags.

**Comment by phuslu** [comment]
Also needs uint64 support, so I sent a https://github.com/valyala/quicktemplate/pull/78 @valyala Could you please take a look?

**Comment by valyala** [comment]
@phuslu , pull request #78 has been merged! The `{%dul uint64 %}` template placeholder is available starting from [v1.6.0](https://github.com/valyala/quicktemplate/tree/v1.6.0).
