### ISSUE TITLE
don't work {% case []string %} inside {% switch r.(type) %}

### ISSUE THREAD

**Issue by ruslanBik4** [valyala/quicktemplate#77]
Выдает такое:
invalid statement "case []string" at file "views/templates/system/routeTable/table_row.qtpl", line 68, pos 37, token "[]string"

вроде должно же штатно обработать?
С одиночными типами работает только в путь

**Comment by valyala** [comment]
The bug should be fixed in [v1.5.2](https://github.com/valyala/quicktemplate/tree/v1.5.2). @ruslanBik4 , could you verify whether the bug is fixed there?

**Comment by valyala** [comment]
You should run `go get -u github.com/valyala/quicktemplate/qtc` in order to update `qtc` compiler.

**Comment by ruslanBik4** [comment]
Thank. This work
